# Optional: commit this to your repo root so Netlify picks it up automatically
[build]
  publish = "."
  command = ""

# Uncomment if you want SPA-style catch-all routing
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
